Docs fixes about Slide's processed_path
histolab/histolab pull request #276
Opened 2021-06-24 10:25 UTC by alessiamarcolini

2021-06-24 12:23 UTC, ernestoarbitrio requested changes
Per comments

2021-06-24 12:23 UTC, ernestoarbitrio commented on src/histolab/slide.py
> +        """Retrieve the path to store the tiles generated from the slide.
I think that considering that this is a lazy property the docstring shouldn't contain the word Retrieve cause it doesn't retrieve anything it's a property

2021-06-24 12:58 UTC, ernestoarbitrio requested changes
Last iteration sorry 🙂

2021-06-24 12:58 UTC, ernestoarbitrio commented on src/histolab/slide.py
> +        """Return the slide name without extension.
A property doesn't compute any action it's a property and for this the docstring should be something without the verbs. I'd use Slide name without extension.

2021-06-24 12:58 UTC, ernestoarbitrio commented on src/histolab/slide.py
> +        """Return the path to store the tiles generated from the slide.
Same

2021-06-28 11:10 UTC, alessiamarcolini commented
@ernestoarbitrio I updated all the docstrings of lazyproperties, requested review

2021-06-29 18:15 UTC, ernestoarbitrio approved these changes
LGTM :)

2021-06-29 18:16 UTC, merged