Add RGB to OD filter
histolab/histolab pull request #290
Opened 2021-07-19 15:49 UTC by alessiamarcolini

## Description

Add RGB to OD filter

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #289

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/histolab/histolab/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-19 15:57 UTC, nicolebussola approved these changes
LGTM

2021-07-19 16:07 UTC, ernestoarbitrio requested changes
Just 2 code style tweaks

2021-07-19 16:07 UTC, ernestoarbitrio commented on tests/unit/filters/test_image_filters.py
> +        assert type(rgb_to_od(image)) == PIL.Image.Image
```suggestion
        assert isinstance(rgb_to_od(image), PIL.Image.Image)
```

2021-07-21 14:06 UTC, ernestoarbitrio approved these changes

2021-07-21 14:11 UTC, merged