add intro and example of stain norm docs
histolab/histolab pull request #506
Opened 2023-01-14 16:07 UTC by nicolebussola

## Description

Update documentation with stain normalization methods (Macenko and Reinhard)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

* Fixes:

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/histolab/histolab/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-16 08:27 UTC, ernestoarbitrio commented
IMHO I'd add an example of the usage of the stain normalizer

2023-01-17 08:57 UTC, alessiamarcolini commented
Hi @nicolebussola I agree with @ernestoarbitrio, a usage example would be great!

2023-01-17 08:57 UTC, alessiamarcolini requested changes

2023-01-17 08:57 UTC, alessiamarcolini commented on docs/api/stain_normalizer.rst
> +The ``stain_normalizer`` module collects methods for to transfer the staining style of an image (target) to another image (source).
```suggestion
The ``stain_normalizer`` module collects methods to transfer the staining style of an image (target) to another image (source).
```

2023-01-17 15:20 UTC, ernestoarbitrio commented
> @nicolebussola ehm the docs are not rendering the API docs and the example (you can see the readthedocs check), can you fix this please?

I can see the page @alessiamarcolini  https://histolab--506.org.readthedocs.build/en/506/api/stain_normalizer.html

2023-01-17 15:25 UTC, alessiamarcolini commented
@ernestoarbitrio yes the page does exist, **the docs are not rendering the API docs and the example**

2023-01-17 15:54 UTC, ernestoarbitrio commented
> @ernestoarbitrio yes the page does exist, **the docs are not rendering the API docs and the example**

what do you see? I do see this:
![image](https://user-images.githubusercontent.com/4196091/212946143-40b71824-2098-4c70-9f23-a0118ef7fc28.png)
is ☝🏽 wrong?

2023-01-17 16:39 UTC, alessiamarcolini requested changes

2023-01-17 16:39 UTC, alessiamarcolini commented on docs/api/stain_normalizer.rst
> +The stain normalization methods can be used to tranfer the staining's appereance of any histology image. First, we need to establish the image to be used as style reference, and the image to be trans
```suggestion
The stain normalization methods can be used to tranfser the staining's appearance of any histology image. First, we need to establish the image to be used as a style reference, and the image to be transformed accordingly:
```

2023-01-17 16:39 UTC, alessiamarcolini commented on docs/api/stain_normalizer.rst
> +The chosen stain normalization method must be then fit on the target image and then applied to the source image:
```suggestion
The chosen stain normalization method must be first fit on the target image and then applied to the source image:
```

2023-01-17 17:58 UTC, alessiamarcolini requested changes
ouch typo for the correction of the typo, my bad

2023-01-17 17:58 UTC, alessiamarcolini commented on docs/api/stain_normalizer.rst
> +The stain normalization methods can be used to tranfser the staining's appearance of any histology image. First, we need to establish the image to be used as a style reference, and the image to be tr
```suggestion
The stain normalization methods can be used to transfer the staining's appearance of any histology image. First, we need to establish the image to be used as a style reference, and the image to be transformed accordingly:
```

2023-01-17 19:58 UTC, merged

2023-07-19 04:11 UTC, hannah413 commented
when will these features be made available in a conda package? i'd implement them in my pipelines today if they were available.

2023-07-19 07:49 UTC, alessiamarcolini commented
Hi @hannah413 
this PR only introduces changes to the documentation, the features are already included in our latest release :)

2023-07-19 20:27 UTC, hannah413 commented
@alessiamarcolini hmm. histolab 0.5.1 is the most up to date version available on conda. i have histolab 0.5.1 installed and can run tissue extraction with it, but when i try to import a stain normalizer like this it says the module doesn't exist:

---------------------------------------------------------------------------
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from histolab.stain_normalizer import ReinhardStainNormalizer

ModuleNotFoundError: No module named 'histolab.stain_normalizer'
```

2023-07-20 10:31 UTC, alessiamarcolini commented
@hannah413 it looks like the latest 0.6.0 release is only available on PyPI for some reason 🤔 on it!

2023-07-21 19:53 UTC, hannah413 commented
@alessiamarcolini thank you!!!